### ISSUE TITLE
Cannot create Column with 'F' format

### ISSUE THREAD

**Issue by mauriceleutenegger** [spacetelescope/PyFITS#100]
I would like to create an ASCII FITS table containing a column specifically with an 'F' format (for example, I would like a human readable wavelength column that says 18.9689 instead of 1.89689E+1).

On this page the documentation for PyFITS 3.3 claims that I should be able to do this in the same way as creating a binary table with a column of 'E' format, as long as I use TableHDU.from_columns() instead of BinTableHDU.from_columns(), and also set ascii=True for all of my Columns.

However, if I try to create an appropriate Column:

```
>>> import numpy as np
>>> import pyfits as pf
>>> print pf.__version__
3.3
>>> a = np.array([1.1,2.2,3.3])
>>> c = pf.Column (array=a,format='F', ascii=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mleutene/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pyfits/column.py", line 482, in __init__
    array = self._convert_to_valid_data_type(array)
  File "/Users/mleutene/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pyfits/column.py", line 845, in _convert_to_valid_data_type
    new_format = _convert_format(format.format)
  File "/Users/mleutene/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pyfits/column.py", line 1937, in _convert_format
    return _convert_fits2record(format)
  File "/Users/mleutene/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pyfits/column.py", line 1834, in _convert_fits2record
    repeat, dtype, option = _parse_tformat(format)
  File "/Users/mleutene/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pyfits/column.py", line 1689, in _parse_tformat
    raise VerifyError('Format %r is not recognized.' % tform)
pyfits.verify.VerifyError: Format 'F' is not recognized.
```

Thanks,

Maurice

**Comment by embray** [comment]
Hi @mauriceleutenegger ,

Sorry for the late reply--I've been traveling the last week.  This was fixed recently in astropy/astropy#3422, though the fix has not been backported to a PyFITS release yet.  However, that still won't totally help you with getting a "human readable" ASCII table in FITS, due to this open issue: astropy/astropy#3428, the gist of which is that it does not by default write a newline at the end of rows in ASCII tables (this is allowed by the format, but is not a requirement either, so it currently takes the path of least action by default, though it would be nice to have a fix for that).

One workaround is to arrange things so that the rows of your table are exactly 80 characters wide--this is good for viewing FITS files as plain text due to the width of (and lack of newlines in) FITS headers.

Hope that helps at least a little.

**Comment by mauriceleutenegger** [comment]
Hi Erik,

sorry, I didn't see the dupe bug since I was only searching issues in
spacetelescope/PyFITS. Is PyFITS deprecated in favor of astropy.io.fits?

Thanks,

Maurice

**Comment by pllim** [comment]
> Is PyFITS deprecated in favor of astropy.io.fits?

Yes. Please see http://www.stsci.edu/institute/software_hardware/pyfits/

**Comment by embray** [comment]
No need for apologies--it's not really obvious, even to me, that the two issues are related.

**Comment by embray** [comment]
I plan to do at least one more release of PyFITS stand-alone, but it will be a pretty minor one (basically most things that have been fixed in Astropy in the last year or so). And then that will probably be it modulo some high level institutional demand (and the support to do so).
