### ISSUE TITLE
deprecation of PyFITS - main documentation page

### ISSUE THREAD

**Issue by MSeifert04** [spacetelescope/PyFITS#112]
The [official documentation](http://pythonhosted.org/pyfits/) doesn't include a deprecation warning. One actually has to go to the [User support](http://pythonhosted.org/pyfits/#user-support) section and click the link there to "find" it.

Maybe these docs should contain a deprecation note like the one on http://www.stsci.edu/institute/software_hardware/pyfits. But maybe not. Feel free to close this issue if you don't plan to do that. :)

**Comment by pllim** [comment]
Thanks for the report, @MSeifert04 !

@SaraOgaz is working on moving all the old docs around. Sara, is this part of your stuff? If not, we need to figure out who has the http://pythonhosted.org/pyfits/ account offline.

**Comment by SaraOgaz** [comment]
I will be taking it down at some point, but I still need to track down who owns it... haven't had time to look into it yet.

**Comment by SaraOgaz** [comment]
I will come back and close the issue when I get to it, so leaving it open for now.

**Comment by embray** [comment]
In theory anyone who has ownership of the pyfits project on pypi.python.org should be able to update this.  That includes me, @perrygreenfield @jhunkeler, and others (and maybe I should be removed??).

I say *in theory* because right now this is tricky because PyPI is in the process of being migrated to the new site, pypi.org and to aid in the migration a lot of services have been disabled.  This includes uploading new docs to pythonhosted.org (which has long been considered for deprecation).  So it's actually not possible to upload new docs to pythonhosted.org right now.  For similar reasons it's no longer possible to edit the metadata of existing releases (pypa/packaging-problems#97).

What we might be able to do is make a kind of pseudo-release of PyFITS (v3.4.1) which only updates the package description in the package metadata to emphasize this more strongly (though it does already have a note about it).  The option is also given to outright delete the pythonhosted.org docs, but I'd be wary of that...

**Comment by SaraOgaz** [comment]
Thanks for the info @embray. I"m closing this issue for now in order to archive this repo. But I will DEFINITELY be following up on this in the coming months.
